feat: implement `CairoLayout`
keep-starknet-strange/ziggy-starkdust pull request #233
Opened 2023-12-05 23:21 UTC by tcoratger

Should close #228.

2023-12-05 23:26 UTC, tcoratger commented
@lana-shanghai As this is `CairoLayout` and it is possible, in unit tests, to check each parameter in a hardcoded way, I did it. This is obviously a lot of lines of code but this way we are 100% sure and we will always see any changes. Don't hesitate to tell me if it's too many tests I can refactor, but I said to myself that I might as well test everything.

2023-12-07 14:09 UTC, lana-shanghai requested changes

2023-12-07 14:09 UTC, lana-shanghai commented on src/lib.zig
> +    pub usingnamespace @import("vm/types/layout.zig");
Let's make sure we finish implementing the builtins before we touch the layout topic

2023-12-07 14:09 UTC, lana-shanghai commented on src/vm/types/layout.zig
> +    pub fn dexInstance() Self {
I think these instance definitions are redundant at the moment, let's discuss the ones we need after the builtins for the milestone. We also have to establish a commit which marks the end of the first milestone.

2023-12-09 13:48 UTC, tcoratger commented
@lana-shanghai FYI I just removed the unnecessary layouts leaving only the following layouts:
- Plain
- Small
- All Cairo
- Dynamic (I added it in addition to those that we mentioned yesterday because it is a configurable layout which could be useful very soon in my opinion)

2023-12-12 23:08 UTC, lana-shanghai approved these changes
lgtm

2023-12-12 23:09 UTC, merged