feat: poseidon builtin runner
keep-starknet-strange/ziggy-starkdust pull request #319
Opened 2024-01-18 12:17 UTC by StringNick

2024-01-19 09:10 UTC, tcoratger commented on src/vm/builtins/builtin_runner/poseidon.zig
> +        }
```zig
if (self.cache.get(address)) |felt| return .{ .felt = felt };
```

2024-01-19 09:10 UTC, tcoratger commented on src/vm/builtins/builtin_runner/poseidon.zig
> +            @intCast(self.n_input_cells),
Here as `n_input_cells` is u32 and you want to cast to usize, I don't think that you have to write that, type coercion should be automatic and implicit with

```zig
if (index < self.n_input_cells)
```

2024-01-19 09:10 UTC, tcoratger commented on src/vm/builtins/builtin_runner/poseidon.zig
> +            return result;
You can remove this return as long as you also return `result` after your if statement no?

2024-01-19 21:55 UTC, jobez reviewed
one comment about a doc string, as well as you are missing an impl of `getMemorySegmentAddresses`

please follow this diff for conventions on how to line it up to the cairo_runner: https://github.com/keep-starknet-strange/ziggy-starkdust/pull/324/files

2024-01-20 00:04 UTC, StringNick commented
@jobez  done

2024-01-23 21:23 UTC, jobez commented
@StringNick lets resolve conflicts here and should be good to merge!

2024-01-23 21:28 UTC, StringNick commented
> @StringNick lets resolve conflicts here and should be good to merge!

done

2024-01-23 22:13 UTC, jobez requested changes

2024-01-23 22:13 UTC, jobez commented on src/vm/builtins/builtin_runner/builtin_runner.zig
> +            .Poseidon => |*poseidon| try poseidon.deduceMemoryCell(allocator, address, memory),
one more ask: see in this change where we added a `getMemorySegmentAddresses` for the builtin_runner

we want to add this completed poseidons impl of `getMemorySegmentAddresses` there, then lgtm!

2024-01-24 01:18 UTC, jobez approved these changes
lgtm

2024-01-24 01:18 UTC, merged